rx7_user:
    resource: "@Rx7UserBundle/Resources/config/routing.yml"
    prefix:   /

index:
    path:      /
    defaults:  { _controller: "Rx7BookBundle:Book:index", page: 1 }


rx7_book:
    resource: "@Rx7BookBundle/Resources/config/routing.yml"
    prefix:   /book

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: "Rx7UserBundle:Security:login" }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout