jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Rx7\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        main:
             id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous: true
            provider:  main
            form_login:
                login_path:    fos_user_security_login
                check_path:    fos_user_security_check
            logout:
                path:    fos_user_security_logout
                target:    /book
            remember_me:
                key:        %secret%  


