security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous: true
            provider:  in_memory
            form_login:
                login_path:    login
                check_path:    login_check
            logout:
                path:    logout
                target:    /book  


