jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        in_memory:
            memory:
                users:
                    auteur:  { password: pass, roles: [ 'ROLE_AUTEUR' ] }
                    moderateur:  { password: pass, roles: [ 'ROLE_MODERATEUR' ] }
                    admin: { password: pass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous: true
            provider:  in_memory
            form_login:
                login_path:    login
                check_path:    login_check
            logout:
                path:    logout
                target:    /book  


