<?php

namespace Rx7\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
	public function findLastBooks($number){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('b')
			->from('Rx7BookBundle:book', 'b')
			->orderBy('b.purchaseDate','DESC')
			->setMaxResults($number);
		return $qb->getQuery()->getResult();
	}
	
}
