rx7book_accueil:
    path:      /
    defaults:  { _controller: "Rx7BookBundle:Book:index" }

rx7book_voir:
    path:      /show/{id}
    defaults:  { _controller: "Rx7BookBundle:Book:show" }

rx7book_ajouter:
    path:      /add
    defaults:  { _controller: "Rx7BookBundle:Book:add" }