<?php

namespace Rx7\BookshelfBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookshelfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookshelfRepository extends EntityRepository
{
}
