rx7_bookshelf_add:
    path:     /add
    defaults: { _controller: "Rx7BookshelfBundle:Bookshelf:add" }

rx7bookshelf_show:
    path:     /add
    defaults: { _controller: "Rx7BookshelfBundle:Bookshelf:add" }