rx7bookshelf_index:
    path:    /
    defaults: { _controller: "Rx7BookshelfBundle:Bookshelf:index" }
    
rx7_bookshelf_add:
    path:     /add
    defaults: { _controller: "Rx7BookshelfBundle:Bookshelf:add" }

rx7bookshelf_show:
    path:     /show/{id}
    defaults: { _controller: "Rx7BookshelfBundle:Bookshelf:show" }
    requirements:
        id: \d*
    
rx7bookshelf_update:
    path:     /update/{id}
    defaults: { _controller: "Rx7BookshelfBundle:Bookshelf:update" }
    requirements:
        id: \d*

rx7bookshelf_addShelf:
    path:     /addShelf/{id}
    defaults: { _controller: "Rx7BookshelfBundle:Bookshelf:addShelf" }
    requirements:
        id: \d*
